
INSERT INTO public.oportunidades (titulo, descricao, tipo, local, municipio, data_evento, horario, duracao, remuneracao, cena_coins, requisitos, vagas, prazo_inscricao, criador_nome, status, area_cultural, exibir_vitrine, meta_captacao, captacao_atual, mostrar_progresso) VALUES
('Festival de Jazz do Recôncavo', 'Festival reunindo músicos de jazz e MPB do Recôncavo Baiano, com três dias de apresentações ao vivo, workshops e jam sessions.', 'evento', 'Centro Cultural de Cachoeira', 'Cachoeira - BA', '2026-05-15', '18:00', 'long', 5000, 50, 'Experiência com jazz ou MPB, mínimo 2 anos de palco', 8, '2026-04-30', 'Maria Santos', 'ativa', 'musica', true, 45000, 18500, true),
('Documentário Vozes do Sertão', 'Produção audiovisual que registra histórias de artistas populares do sertão nordestino, preservando a memória cultural da região.', 'evento', 'Locações no Sertão', 'Feira de Santana - BA', '2026-06-01', '08:00', 'month', 3000, 30, 'Experiência com audiovisual, disponibilidade para viagens', 5, '2026-05-15', 'João Oliveira', 'ativa', 'audiovisual', true, 80000, 32000, true),
('EP Raízes Urbanas', 'Gravação de EP com 6 faixas mesclando ritmos afro-brasileiros com hip-hop e eletrônica, em estúdio profissional.', 'evento', 'Estúdio Sangalo', 'Salvador - BA', '2026-04-20', '14:00', 'week', 2500, 25, 'Instrumentistas e vocalistas com experiência em gravação', 6, '2026-04-10', 'Carlos Drummond', 'ativa', 'musica', true, 35000, 12000, true),
('Exposição Digital Arte Negra', 'Mostra digital interativa celebrando a arte negra contemporânea com realidade aumentada e instalações imersivas.', 'evento', 'MAM - Museu de Arte Moderna', 'Salvador - BA', '2026-07-10', '10:00', 'long', 4000, 40, 'Artistas visuais com portfólio digital', 12, '2026-06-20', 'Ana Beatriz', 'ativa', 'artes_visuais', true, 60000, 45000, true),
('Show Acústico Mulheres na Música', 'Série de shows acústicos protagonizada por mulheres artistas, valorizando composições autorais e a diversidade musical.', 'evento', 'Teatro Vila Velha', 'Salvador - BA', '2026-05-08', '20:00', 'oneday', 1500, 15, 'Mulheres musicistas com repertório autoral', 4, '2026-04-25', 'Fernanda Lima', 'ativa', 'musica', true, 20000, 8000, true),
('Vaga de Produtor Cultural', 'Oportunidade para produtor cultural atuar na organização de eventos e projetos artísticos no Pelourinho.', 'vaga', 'Pelourinho', 'Salvador - BA', NULL, '09:00 - 18:00', 'long', 3500, 0, 'Graduação em Produção Cultural ou áreas afins, experiência mínima de 1 ano', 2, '2026-04-15', 'Instituto Cultural BA', 'ativa', 'cultura_popular', true, NULL, 0, false),
('Teatro Memórias de Minha Terra', 'Montagem teatral baseada em relatos orais de comunidades quilombolas, com elenco local e trilha sonora original.', 'evento', 'Teatro Castro Alves', 'Salvador - BA', '2026-08-05', '19:30', 'week', 3500, 35, 'Atores e atrizes com experiência em teatro comunitário', 10, '2026-07-15', 'Grupo Teatral Axé', 'ativa', 'teatro', true, 55000, 22000, true),
('Festival LGBTQ+ de Artes', 'Festival multidisciplinar celebrando a arte e cultura LGBTQ+ com performances, exposições, debates e shows.', 'evento', 'Parque da Cidade', 'Salvador - BA', '2026-06-28', '16:00', 'week', 2000, 20, 'Artistas de qualquer linguagem artística', 15, '2026-06-10', 'Coletivo Diversidade', 'ativa', 'danca', true, 40000, 15000, true),
('Vaga de Designer Gráfico Cultural', 'Profissional para criar identidades visuais e materiais de divulgação para projetos culturais na Bahia.', 'vaga', 'Home Office', 'Salvador - BA', NULL, 'Flexível', 'month', 2800, 0, 'Portfólio com trabalhos culturais, domínio de Adobe Creative Suite', 1, '2026-04-20', 'Agência Cultura Viva', 'ativa', 'artes_visuais', true, NULL, 0, false),
('Álbum do Sertão - Forró Raiz', 'Gravação de álbum com 12 faixas de forró tradicional, resgatando compositores clássicos do sertão nordestino.', 'evento', 'Estúdio Nordeste Som', 'Caruaru - PE', '2026-05-20', '10:00', 'month', 2000, 20, 'Músicos com vivência em forró pé-de-serra', 8, '2026-05-05', 'Trio Baião Raiz', 'ativa', 'musica', true, 50000, 28000, true);
