// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlbfffvcjzuudgpnuhab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYmZmZnZjanp1dWRncG51aGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMDAxNTEsImV4cCI6MjA4MjY3NjE1MX0.agtjuCFtv8KDK8jKrKUAytyAf0S2_R1ZnqOUVKwJS3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});